name: Build Arch Package

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: archlinux
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install base-devel
        run: sudo pacman -Sy --noconfirm base-devel python python-pip

      - name: Install Python dependencies from setup.py
        run: pip install .  # This installs the package and its dependencies from setup.py

      - name: Build the package
        run: makepkg -si --noconfirm

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: 'v1.0.0'  # Set your versioning scheme
          release_name: '${{ github.event.repository.name }} - Version 1.0.0'
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Arch Package
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: *.pkg.tar.zst  # Adjust to the actual output location
          asset_name: music_downloader.pkg.tar.zst  # Specify a proper name for your asset
          asset_content_type: application/octet-stream
